# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='key',
            field=models.CharField(max_length=50, verbose_name='类别键名'),
        ),
    ]
